export const SET_HERO_LIFE = 'SET_HERO_LIFE';
export const SET_VILLAIN_LIFE = 'SET_VILLAIN_LIFE';
export const SET_HERO_POINTS = 'SET_HERO_POINTS';
export const SET_VILLAIN_POINTS = 'SET_VILLAIN_POINTS';
export const SET_MESSAGE = 'SET_MESSAGE';